### ISSUE TITLE
Unable to Patch Generic FBX

### ISSUE THREAD

**Issue by Adjerry91** [HashEdits/Face-Tracking-Patcher#4]
The edit distribution tools does not work with trying to patch base heads in Unity. Base heads are usually generic rig configuration and looks like the builder will not allow you patch with that type.

**Comment by HashEdits** [comment]
Added support for that alongside your contributions in the [latest release](https://github.com/HashEdits/EditDistributionTools/releases/tag/EditDistributionTools-V2.3).

Should work for your use case but I'll wait for your green flag to confirm that it's indeed solved
